baseurl: ''
url: 'https://lebeninmobiliaria.com'
name: 'lebeninmobiliaria.com'
author: LEBEN Inmobiliaria
tel1: "+573160520942"
tel2: "+573224736189"
whatsapp: https://api.whatsapp.com/send?phone=+573224736189&text=Hola!%20Estaba%20en%20la%20p%C3%A1gina%20web%20de%20LEBEN.%20Por%20favor,%20env%C3%ADame%20m%C3%A1s%20info%20sobre...
email: contactolebeninmobiliaria@gmail.com
maps: https://maps.app.goo.gl/LAmA8gQZFBxwKak28
facebook_url: https://www.facebook.com/lebeninmobiliaria

markdown: kramdown

permalink: :slug

compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []

collections:
  ventas:
    output: true
    permalink: /ventas/:path
  arriendo:
    output: true
    permalink: /arriendo/:path
  posts:
    output: true
    permalink: /blog/:slug
