baseurl: ''
url: 'https://lebeninmobiliaria.com'
title: 'lebeninmobiliaria.com'
author: LEBEN Inmobiliaria
tel1: "573160520942"
tel2: "573224736189"
whatsapp: https://wa.me/573224736189&text=Hola!%20Estaba%20en%20la%20p%C3%A1gina%20web%20de%20LEBEN.%20Por%20favor,%20env%C3%ADame%20m%C3%A1s%20info%20sobre...
email: contactolebeninmobiliaria@gmail.com
maps: https://maps.app.goo.gl/LAmA8gQZFBxwKak28
facebook_url: https://www.facebook.com/lebeninmobiliaria

markdown: kramdown

permalink: :slug

compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []

collections:
  ventas:
    output: true
    permalink: /ventas-casas-y-apartamentos/:path
  arriendo:
    output: true
    permalink: /arriendo-casas-y-apartamentos/:path
  posts:
    output: true
    permalink: /blog/:slug

# Asegúrate de que tienes esta línea para habilitar los plugins en GitHub Pages
plugins:
  - jekyll-redirect-from

# Configuración opcional para personalizar el comportamiento del plugin
redirect_from:
  # Habilita la generación de redirecciones alternativas (no es necesario en la mayoría de los casos)
  # enabled: true

  # Ignora las redirecciones especificadas (útil si tienes conflictos)
  # ignore:
  #   - /ignorar-esta-redireccion

whitelist:
  - jekyll-redirect-from

github: [metadata]

# Excluir archivos y carpetas
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/