baseurl: ''
url: 'https://lebeninmobiliaria.com'
name: 'lebeninmobiliaria.com'
author: LEBEN
tel1: "3224736189"
tel2: "3160520942"
whatsapp: https://api.whatsapp.com/send?phone=+573160518574&text=Hola!%20Estaba%20en%20la%20p%C3%A1gina%20web%20de%20LEBEN.%20Por%20favor,%20env%C3%ADame%20m%C3%A1s%20info%20sobre...
email: contactolebeninmobiliaria@gmail.com
facebook_url: https://www.facebook.com/lebeninmobiliaria

markdown: kramdown

permalink: :slug

keep_files: [/img]

compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []

collections:
  ventas:
    output: true
    permalink: /ventas/:path
  posts:
    output: true
    permalink: /blog/:slug