# config.yml
backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: 'assets/images'
public_folder: 'images'
collections:
  - name: 'venta'
    label: 'Venta'
    folder: '_ventas/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'venta' }
      - { label: 'Meta Título', name: 'title', widget: 'string' }
      - { label: 'Meta descripción', name: 'description', widget: 'string' }
      - { label: 'Título para la propiedad', name: 'h1', widget: 'string' }
      - label: "Categoría"
        name: "clase"
        widget: "select"
        options: ["apartamentos", "apartaestudios", "casas", "fincas", "quintas"]
      - { label: 'Imagen principal mínimo 1024px y formato WEBP', name: 'img', widget: 'image' }
      - { label: 'Texto breve que describe la imagen', name: 'alt', widget: 'string' }
      - { label: 'Texto breve para llamado a la acción', name: 'cta', widget: 'string' }
      - { label: 'Precio con puntos de miles y coma de millón', name: 'precio', widget: 'string' }
      - { label: 'Nombre de la propiedad en minúscula', name: 'propiedad', widget: 'number' }
      - { label: 'Subtítulo breve para presentar la propiedad', name: 'intro', widget: 'string' }
      - {label: Area total, name: area, widget: string}
      - {label: Habitaciones, name: habitacion, widget: string}
      - {label: Sala, name: sala, widget: string}
      - {label: Comedor, name: comedor, widget: string}
      - {label: Cocina, name: cocina, widget: string}
      - {label: Baños, name: bano, widget: string}
      - {label: Garage, name: garage, widget: string}
      - {label: Servicios, name: servicios, widget: string}
      - label: "Características adicionales"
        name: "adicional"
        widget: "list"
        allow_add: true
        field: {label: Descripción, name: característica, widget: string}
      - label: "Gallery"
        name: "galleryImages"
        widget: "list"
        summary: '{{fields.image}}'
        field: {label: Image, name: image, widget: image}
      - { label: 'Body', name: 'body', widget: 'markdown' }
- name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }